### ISSUE TITLE
SIDD datasets

### ISSUE THREAD

**Issue by hristine1224** [nagejacob/SpatiallyAdaptiveSSID#14]
![微信截图_20240718145159](https://github.com/user-attachments/assets/8223f525-9555-4787-b367-67b62305ce66)
想请教一下，这3个mat文件具体是在SIDD官网哪里下载的，谢谢

**Comment by nagejacob** [comment]
In this [link](https://abdokamel.github.io/sidd/)

**Comment by hristine1224** [comment]
谢谢！

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
