### ISSUE TITLE
Inference Question

### ISSUE THREAD

**Issue by Jason-ic** [nagejacob/SpatiallyAdaptiveSSID#15]
Hello. When I in the phase of inference, I load the model, but I get the error, how to fix it? thx
Traceback (most recent call last):
  File "/tmp/pycharm_project_602/validate/validate_SIDD.py", line 65, in <module>
    main(opt)
  File "/tmp/pycharm_project_602/validate/validate_SIDD.py", line 46, in main
    model.load_model('/tmp/pycharm_project_602/pretrained_models/UNet.pth')
  File "/tmp/pycharm_project_602/model/three_stage.py", line 149, in load_model
    self.iter = load_dict['iter']
KeyError: 'iter'

**Comment by Jason-ic** [comment]
and I check the keys of model, it doesn't have this keys, and other keys, such as 'BNN', 'LAN' et.

**Comment by nagejacob** [comment]
Model.save_model()/load_model() are used to save and resume training, which handle the iteration, optimizers and network checkpoints, see line 124-154 in model/three_stage.py. In your case, you want to just load the network checkpoint of UNet, you could set the path in line 24 of option/three_stage.json.

**Comment by Jason-ic** [comment]
> Model.save_model()/load_model() are used to save and resume training, which handle the iteration, optimizers and network checkpoints, see line 124-154 in model/three_stage.py. In your case, you want to just load the network checkpoint of UNet, you could set the path in line 24 of option/three_stage.json.

So in the phase of inference, I dont need to use the function of load_model(), just use the model.validation_step(), is that right?

**Comment by Jason-ic** [comment]
And I just want to inference  some noise picture, and then I want to get the denosing result in format of picture, I want to know how to implement, thx

**Comment by nagejacob** [comment]
Yes, just use model.validation_step(). You could modify the validate/validate_SIDD.py to load one image, perform inference, then save the image. The utils for loading/saving images could be found in utils/io.py.

**Comment by Jason-ic** [comment]
> Yes, just use model.validation_step(). You could modify the validate/validate_SIDD.py to load one image, perform inference, then save the image. The utils for loading/saving images could be found in utils/io.py.

I'm so sorry to bother you again, I modify the validate/validate_SIDD.py to load a picture, and I use the utils in the io.py to transform the picture to tensor, then I use model.validation_step(image), but I get the error: RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 134 but got size 135 for tensor number 1 in the list.
could you tell me how to tackle the input image in detail, thx

**Comment by Jason-ic** [comment]
and I modify the funtion validation_step(), I change the input = data['L'] into input = data, because my image doesnt have the L the data is the tensor that I use the funtion io.image2tensor(image)

**Comment by nagejacob** [comment]
Your input image should be divisible by 32 as U-Net would perform downsampling and upsampling. You could pad your input image to match the requirement.

**Comment by Jason-ic** [comment]
> Your input image should be divisible by 32 as U-Net would perform downsampling and upsampling. You could pad your input image to match the requirement.

yeah, I get it! very thx
