### ISSUE TITLE
Results question

### ISSUE THREAD

**Issue by Jason-ic** [nagejacob/SpatiallyAdaptiveSSID#16]
Hello. when I load one image to inference, I get the result, but it's very terrible, Is there something wrong with me? my inference code is follwing:
'''
def validate_sidd(model, image_dir, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    for image_name in tqdm.tqdm(sorted(os.listdir(image_dir))):
        image_path = os.path.join(image_dir, image_name)
        image = io.image2tensor(image_path)
        b, c, h, w = image.shape
        img_h_64 = int(64 * np.ceil(h / 64.0))
        img_w_64 = int(64 * np.ceil(w / 64.0))
        image = F.pad(image, (0, img_w_64 - w, 0, img_h_64 - h), padding_mode='reflect')
        output = model.validation_step(image)
        output_path = os.path.join(out_dir, image_name)
        io.tensor2image(output, output_path)

def main(opt):
    Model = getattr(__import__('model'), opt['model'])
    model = Model(opt)
    model.data_parallel()

    validate_sidd(model, './data/test', './data/results')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Validate the denoiser")
    parser.add_argument("--config_file", type=str, default='../option/three_stage.json')
    argspar = parser.parse_args()

    opt = parse(argspar.config_file)
    # recursive_print(opt)

    main(opt)
'''

**Comment by nagejacob** [comment]
Try this output = model.validation_step(image * 255) / 255

**Comment by Jason-ic** [comment]
> Try this output = model.validation_step(image * 255) / 255

oh, very thx, it's OK
