### ISSUE TITLE
about .mat file

### ISSUE THREAD

**Issue by chensming** [nagejacob/SpatiallyAdaptiveSSID#2]
Hi, I am interested in your nice work. But I don't know how to convert png to .mat (For example, sometimes I want to see what the original image looks like). I would appreciate if you could answer this question.

**Comment by nagejacob** [comment]
Does the 'original image' means the raw camera output? If so, the png can not revert to 'original image' due to lack of ISP model and parameters. However, the original image of SIDD dataset could be downloaded from their website (http://130.63.97.225/share/sidd_dng/) as DNG files.

**Comment by chensming** [comment]
> Does the 'original image' means the raw camera output? If so, the png can not revert to 'original image' due to lack of ISP model and parameters. However, the original image of SIDD dataset could be downloaded from their website (http://130.63.97.225/share/sidd_dng/) as DNG files.

Oh, I just want to know how to prepare the dataset like these structure:
![image](https://github.com/nagejacob/SpatiallyAdaptiveSSID/assets/45591767/c1867b5b-8168-434e-b854-ce8b988c2b2c)

**Comment by nagejacob** [comment]
Please download SIDD Medium Srgb dataset from https://www.eecs.yorku.ca/~kamel/sidd/dataset.php, and download SIDD Validation and Benchmark '.mat' files from https://www.eecs.yorku.ca/~kamel/sidd/benchmark.php.

**Comment by chensming** [comment]
Thanks! You are so kind! And I would like to visualize the '.mat' files(eg. ValidationNoisyBlocksSrgb.mat), could you give me some suggestion? (I 'm sorry that I am new to this field) ^_^

**Comment by nagejacob** [comment]
Try this:
```
import imageio
import numpy as np
import os
import scipy.io as sio

if __name__ == '__main__':
    SIDD_path = '/Users/nagejacob/Documents/datasets/SIDD'
    mat = sio.loadmat(os.path.join(SIDD_path, 'SIDD_Validation/ValidationNoisyBlocksSrgb.mat'))
    noisy_block = mat['ValidationNoisyBlocksSrgb']
    n = noisy_block.shape[0]
    k = noisy_block.shape[1]
    for i in range(n):
        for j in range(k):
            img = noisy_block[i, j]
            print('extracting %d_%d.png' % (i, j))
            imageio.imwrite('%d_%d.png' % (i, j), img)            
```
And I advice you to search on google first to solve these common problems.

**Comment by chensming** [comment]
> Try this:
> 
> ```
> import imageio
> import numpy as np
> import os
> import scipy.io as sio
> 
> if __name__ == '__main__':
>     SIDD_path = '/Users/nagejacob/Documents/datasets/SIDD'
>     mat = sio.loadmat(os.path.join(SIDD_path, 'SIDD_Validation/ValidationNoisyBlocksSrgb.mat'))
>     noisy_block = mat['ValidationNoisyBlocksSrgb']
>     n = noisy_block.shape[0]
>     k = noisy_block.shape[1]
>     for i in range(n):
>         for j in range(k):
>             img = noisy_block[i, j]
>             print('extracting %d_%d.png' % (i, j))
>             imageio.imwrite('%d_%d.png' % (i, j), img)            
> ```
> 
> And I advice you to search on google first to solve these common problems.

Oh， thanks a lot!
