### ISSUE TITLE
SSIM result on SIDD val dataset

### ISSUE THREAD

**Issue by p1y2z3** [nagejacob/SpatiallyAdaptiveSSID#5]
请问一下您可以补充“validate_SIDD.py”中测SSIM的代码吗，我怎么测都比别人低0.05，包括在您这里也是，好恼火。 我想检查一下我哪里出错了，如果可以的话非常感谢。

**Comment by nagejacob** [comment]
You may use the matlab script in [MPRNet](https://github.com/swz30/MPRNet/blob/main/Denoising/evaluate_SIDD.m)

**Comment by p1y2z3** [comment]
非常感谢！
