### ISSUE TITLE
Is the denoise model could be other methods?

### ISSUE THREAD

**Issue by lll143653** [nagejacob/SpatiallyAdaptiveSSID#6]
This is very meaningful work and very inspiring to me. I found the training code from the historical version of git and successfully reproduced the denoise effect in the article (using unet default), but when I wanted to use other types of denoisers (dncnn, restormer), I found something strange question. After using the same bnn and lan boot and testing on sidd val, the dncnn indicator remained at around 27db, but the restormer had no effect at all. What I changed is where the denoising model is loaded in tree stage.py, and the initial unet was replaced with restormer. This confused me. Is there something wrong with my code implementation?

**Comment by nagejacob** [comment]
I think the dncnn and restormer you used may not be trained. In fact, the denoisers should be firstly trained with the supervision of BNN and LAN. The train code is at https://github.com/nagejacob/SpatiallyAdaptiveSSID/tree/731adb9b5dcc3a860d207436f5fee6f794b2e5f4

**Comment by lll143653** [comment]
thank you~~

**Comment by lll143653** [comment]
Now the model runs as expected
