### ISSUE TITLE
Are there any differences in the impact of different denoisers on the final denoising effect? 

### ISSUE THREAD

**Issue by lll143653** [nagejacob/SpatiallyAdaptiveSSID#7]
I successfully reproduced the author's amazing work, but also encountered a few things that confused me. Specifically, I trained BNN and LAN using SIDD MEDIUM on a single 3090, and each model was trained 400,000 times and saved. Then, I started training the UNet provided in the code. After about 200,000 iterations, the model achieved an index of 37.26db on a total of 1280 upper sub-images of SIDD Val. This is still a certain distance from the index in the paper, but it is not much different. . But when I replaced restormer with UNet, I also tested after about 200,000 iterations, and the indicator I got was 37.19db, so I continued for about 100,000 iterations and found that the training effect remained basically unchanged.

This confuses me because restormer has almost 10 times the computation and 25 times the number of parameters, but performs on par with UNet. Does this mean that the performance of the final denoiser depends on the bnn and lan networks? I am not sure if my idea is correct. I am continuing to verify dncnn. I would like to ask the author whether he has discovered this phenomenon or whether I have made a mistake.

**Comment by lll143653** [comment]
Sorry to bother the author, but I really want to know if there is such a problem

**Comment by lll143653** [comment]
the performance of nafnet after 1700,000 on the sidd val is 36.97db

**Comment by nagejacob** [comment]
The 37.26dB of reproduce is OK as there are three training stage and self-supervised training on SIDD is not that stable. As for the lower performance of distilled Restormer and NAFNet, I experienced the same phenomenon so we use a lightweight U-Net in the paper. I think it is mainly due to the supervision from BNN and LAN are not perfect that U-Net is enougn to learn a tradeoff between BNN and LAN, superior network archtiectures may not provide more performance.

**Comment by nagejacob** [comment]
Besides, to get best overall performance that matches our paper, you could select the best PSNR model when training BNN, it may provide slightly better results.

**Comment by lll143653** [comment]
Thank you for your work. Your work is very valuable. Do you have any similar work for cvpr this year?

**Comment by nagejacob** [comment]
Thanks for your concern. I'v submitted one paper to cvpr but got three weak rejects. That paper is not good enough. I'm still working on self-supervised image denoising and I'll try my best to do better.

**Comment by lll143653** [comment]
Good luck to you, your work is valuable and of practical significance

**Comment by nagejacob** [comment]
Replacing U-Net with Restormer/NAFNet does not provide any improvement, however, implement BNN with Restormer/NAFNet may be benefit for performance. This is not a significant contribution but you could try if you are interested in self-supervised image denoising. Please feel free to communicate with me.

**Comment by lll143653** [comment]
thank you for your reply
